# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/sites/project_mini_games/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(366, 276)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(243, 243, 243);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 182, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.High_text = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.High_text.setFont(font)
        self.High_text.setObjectName("High_text")
        self.verticalLayout.addWidget(self.High_text)
        self.Cross_zero_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Cross_zero_btn.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.Cross_zero_btn.setObjectName("Cross_zero_btn")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Cross_zero_btn)
        self.verticalLayout.addWidget(self.Cross_zero_btn)
        self.Rock_scissors_paper_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Rock_scissors_paper_btn.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.Rock_scissors_paper_btn.setObjectName("Rock_scissors_paper_btn")
        self.buttonGroup.addButton(self.Rock_scissors_paper_btn)
        self.verticalLayout.addWidget(self.Rock_scissors_paper_btn)
        self.Dice_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Dice_btn.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"")
        self.Dice_btn.setObjectName("Dice_btn")
        self.buttonGroup.addButton(self.Dice_btn)
        self.verticalLayout.addWidget(self.Dice_btn)
        self.exit_Button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_Button.setGeometry(QtCore.QRect(270, 190, 81, 23))
        self.exit_Button.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.exit_Button.setObjectName("exit_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 366, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Мини-игры"))
        self.High_text.setText(_translate("MainWindow", "Выберите мини-игру:"))
        self.Cross_zero_btn.setText(_translate("MainWindow", "Крестики-нолики"))
        self.Rock_scissors_paper_btn.setText(_translate("MainWindow", "Камень, ножницы, бумага"))
        self.Dice_btn.setText(_translate("MainWindow", "Кости"))
        self.exit_Button.setText(_translate("MainWindow", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
